# local-pvc = local Persistence Volume Claim
# Creating the necessary PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  namespace: enterprise-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
