apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-depl
  namespace: enterprise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-service
  template:
    metadata:
      labels:
        app: command-service
    spec:
      containers:
        - name: command-service
          image: ismailchbiki/command-service-amd64:v1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: command-clusterip-srv
  namespace: enterprise-app
spec:
  type: ClusterIP
  selector:
    app: command-service
  ports:
    - name: command-service
      protocol: TCP
      port: 80
      targetPort: 80
