apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  namespace: enterprise-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: user-clusterip-srv
                port:
                  number: 80
          - path: /api/kiteschool
            pathType: Prefix
            backend:
              service:
                name: kiteschool-clusterip-srv
                port:
                  number: 80
          - path: /swagger-user # UserService Swagger UI
            pathType: Prefix
            backend:
              service:
                name: user-clusterip-srv
                port:
                  number: 80
          - path: /swagger-kiteschool # KiteschoolService Swagger UI
            pathType: Prefix
            backend:
              service:
                name: kiteschool-clusterip-srv
                port:
                  number: 80
