apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
  namespace: enterprise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ismailchbiki/user-service-amd64:latest
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-clusterip-srv
  namespace: enterprise-app
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: user-service
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kiteschool-hpa
  namespace: enterprise-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
